# Generated by Django 5.0.6 on 2024-06-27 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='phone',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
